### ISSUE TITLE
package install fails since removing project_wham.r

### ISSUE THREAD

**Issue by timjmiller** [timjmiller/wham#15]
When installing from github this error is returned:

 Error: package or namespace load failed for ‘wham’ in namespaceExport(ns, exports):
    undefined exports: project_wham

I find that project_wham.Rd is still in the man directory. Also "export(proj_wham)" is still in the NAMESPACE file.

**Comment by brianstock** [comment]
Hey Tim, anytime you make changes to the roxygen comments you'll have to rebuild the documentation. Button click (or Ctrl + Shift + D) in RStudio, which runs this code:
```
devtools::document(roclets = c('rd', 'collate', 'namespace'))
```
In this case the roxygen comments "changed" in the sense that they were deleted.
