### ISSUE TITLE
Plot option to label ages not beginning with 1

### ISSUE THREAD

**Issue by Charles-Adams-NOAA** [timjmiller/wham#26]
Add an option to label the automated plots with the actual ages

**Comment by brianstock-NOAA** [comment]
Tim wrote all the plot functions to use an `ages.lab` argument... but this is created and stored in the model object on [line 1057](https://github.com/timjmiller/wham/blob/master/R/prepare_wham_input.R#L1057) of `prepare_wham_input` and defaults to `1:n.ages`:

```
ages.lab = paste0(1:data$n_ages, c(rep("",data$n_ages-1),"+"))
```

**Comment by brianstock-NOAA** [comment]
I like that, will do. There will probably be other options that may need to be specified, so I'll add `ages.lab` as an entry in a `plot.opts` list which we can expand in the future.

**Comment by brianstock-NOAA** [comment]
You should be able to manually specify age labels now. E.g. replace [this line in Ex 1](https://timjmiller.github.io/wham/articles/ex1_SNEMA_yellowtail_flounder.html#plot-input-data-diagnostics-and-results) with:

```
plot_wham_output(mod=m4_proj, out.type='html', plot.opts=list(ages.lab = c("0","1","2","3","4","5+")))
```

I did not write any code to catch errors (yet).
