### ISSUE TITLE
Error in integrate(function(x) exp(-(spline(x) - nll))

### ISSUE THREAD

**Issue by Charles-Adams-NOAA** [timjmiller/wham#28]
Running example 2, I got an error running the for loop that begins on line 52. Stepping inside the loop and setting 

m <- 1

it runs fine until fitting model, which gives the following errors while doing OSA residuals

Doing OSA residuals...
[1] 1
Error in integrate(function(x) exp(-(spline(x) - nll)), spline.range[1],  : 
  non-finite function value
.
.
.
[1] 194
Error in integrate(function(x) exp(-(spline(x) - nll)), spline.range[1],  : 
  non-finite function value
Error in `$<-.data.frame`(`*tmp*`, "Fx", value = numeric(0)) : 
  replacement has 0 rows, data has 194
>

**Comment by brianstock-NOAA** [comment]
Hi Chuck,

Strange. Tim and I have now installed WHAM and ran ex2 on two different windows machines without getting this error. It may not be windows-specific like the font family warnings.

What is your output from:
```
library(wham)
library(TMB)
sessionInfo()
```

I wonder if some of your packages are out of date? First thing I'd try is to update your R packages and then reinstall TMB and WHAM. 
```
update.packages(ask=F)
devtools::install_github("kaskr/adcomp/TMB", dependencies=TRUE)
devtools::install_github("timjmiller/wham", dependencies=TRUE)
```

**Comment by Charles-Adams-NOAA** [comment]
Example 2 ran fine after updating to TMB v 1.7.18 and WHAM v 1.0.0
