### ISSUE TITLE
Enable use of previous versions of wham.cpp

### ISSUE THREAD

**Issue by brianstock** [timjmiller/wham#3]
Currently coded so that `wham_v0.cpp` gets compiled when `wham` is installed, resulting in `wham.so` in `<R library>/3.5/wham/libs`. Can then call:
```
wham.dir <- find.package("wham")
dyn.load( paste0(wham.dir,"/libs/", TMB::dynlib("wham")) )
mod <- TMB::MakeADFun(input$data,input$par, DLL="wham", random = input$random, map = input$map)
mod = fit.tmb.fn(mod, n.newton = n.newton, do.sdrep = do.sdrep)
```

This is easiest, as Merrill has in [LIME](https://github.com/merrillrudd/LIME). Better would be like Jim has done for [VAST](https://github.com/James-Thorson/VAST), where all versions of the .cpp file are distributed (`VAST_v1_0_0.cpp`, `VAST_v1_1_0.cpp`, etc.) and you can choose which to use. To-do.

**Comment by brianstock** [comment]
This determines one other difference:
  - VAST compiles the `.cpp` when you run the model, since you have to specify which version and there are a lot of `.cpp` files included.
  - LIME compiles the one `LIME.cpp` when you install the package, so `LIME.so` is ready to use. You can still use a previous/different version of `LIME.cpp`, but you'd have to reinstall a previous version of the `LIME` package via `devtools::install_github("merrillrudd/LIME@<version #>")`. Would make it harder to switch back and forth between versions if you wanted to compare results or figure out a bug.

**Comment by brianstock-NOAA** [comment]
Taking this off the to-do list because I like the approach of having all the R and TMB code together with one version #. Jim's approach in VAST allows different versions of R to be using the same TMB code... .And it's not too hard to reinstall a different version via `install_github`.
