### ISSUE TITLE
Very minor: vignette link not working

### ISSUE THREAD

**Issue by tcarruth** [timjmiller/wham#34]
https://timjmiller.github.io/wham/articles/ex1_basics.html 

Link in Section 3 for TMBhelper::Check_Identifiable()

https://github.com/kaskr/TMB_contrib_R/blob/master/TMBhelper/R/Check_Identifiable.R

Returns a 404 page.

**Comment by brianstock-NOAA** [comment]
Thanks for reporting! I've updated ?fit_tmb, ?fit_wham, and the Ex1 vignette.
