### ISSUE TITLE
do.fit error for butterfish

### ISSUE THREAD

**Issue by brianstock-NOAA** [timjmiller/wham#48]
Error traced to `check_FXSPR` function, line 184 in `fit_wham.R`:
```
mod$fn(mod$opt$par)
```

When `do.fit=F`, `mod$opt$par` is NULL. One guess is that it's caused by the automatic re-ordering of the parameter vector, which didn't used to happen but does now after the re-structuring of `prepare_wham_input`? Could try ordering the parameter vector to match the cpp side.

**Comment by timjmiller** [comment]
Also there are a few places where there are inconsistencies in what "parameters" are passed to $report(). Probably should make this consistent for do.fit=T and do.fit=F

For report
line 77 of fit_tmb.R: mod$report()
line 119 of project_wham.R: mod$report()
line 146 of fit_wham.R: mod$report()
line 159 of fit_wham.R: mod$report()
line 186 of fit_wham_.R: mod$report(mod$env$last.par)
line 211 of fit_wham_.R: mod$report(mod$env$last.par)
line 234 of fit_wham_.R: mod$report(mod$env$last.par)
