### ISSUE TITLE
Different ecov obs error options for multiple ecovs

### ISSUE THREAD

**Issue by brianstock** [timjmiller/wham#52]
It is not currently possible to specify different options for estimating/fixing the ecov obs error if you have multiple ecovs. The [documentation](https://timjmiller.github.io/wham/reference/prepare_wham_input.html) says that you can, but it is wrong. `data$Ecov_obs_sigma_opt` is an integer, not a vector of length `n.ecov`, and `prepare_wham_input` uses, e.g. `ecov$logsigma == 'est_1'` (i.e, does not consider it as a vector).

For the time being, you can manually modify map after calling `prepare_wham_input` to set up models with different ecov obs error options if you want to specify/fix the obs error or estimate one value across years (`"est_1"`). This will not work for the `"est_re"` option... the .cpp needs to be modified to allow some but not all ecovs to estimate the yearly obs errors as RE with estimated mean and variance (described on top right of page 4 in [WHAM paper](https://www.sciencedirect.com/science/article/pii/S0165783621000953)).

**Comment by timjmiller** [comment]
This is now available on devel branch.
