### ISSUE TITLE
Expanding the Dirichlet Multinomial Library

### ISSUE THREAD

**Issue by emilylil** [timjmiller/wham#58]
Hi All,
I'd like to add a few more options for using the Dirichlet-Multinomial to fit composition data. Basically, since this distribution does not allow for 0 observations, I want to make some options akin to "miss0" and "pool" which ignore or pool the 0s, respectively, and already exist for the Dirichlet and Logistic Normal distributions.
This would be my first time forking and contributing to a project, but I think I've identified the right code in age_comp_osa.hpp. I could add:
age_comp_model =10 for dirichlet-multinomial, miss0
age_comp_model =11 for dirichlet-multinomial, pool0

**Comment by timjmiller** [comment]
Convergence with the D-M can be an issue because of the bounds on the estimated over-dispersion term and dependence on the assumed effective sample size. I have been able to obtain convergence by increasing the assumed ESS, but I can't say whether that is a good practice.

**Comment by emilylil** [comment]
Sorry, I see now that ddirmultinom() function does account for 0s by adding 1.0 to observed values before applying the lgamma. 
If I have time in the next few months, and with your permission, I'd like to try adding a few other alternative likelihoods- perhaps conditional log gaussian cox process or tweedie. Both are under study by Noel Cadigan and Jim Thorson, respectively.

**Comment by emilylil** [comment]
I've gone back to using the multinomial and no longer plan to use alternative likelihood structures for my age compositions.
