### ISSUE TITLE
allow same selectivity blocks for different fleets/indices

### ISSUE THREAD

**Issue by timjmiller** [timjmiller/wham#59]
For example, when considering LPUE or CPUE as indices may wish to use the same selectivity assumptions for the fleet and index. This came up in the Plaice research track and can be done outside of the R functionality in WHAM, but it breaks the retrospective pattern functionality.

**Comment by brianstock** [comment]
This is done in the SSWG, https://github.com/timjmiller/SSRTWG/commit/052952fa472fe761dde0900e1d9c9dd08587413b. Need to test before merging into wham/devel.

**Comment by timjmiller** [comment]
specifying selectivity blocks pointers for fleets and indices (either to be the same or not) is possible on devel branch.
