### ISSUE TITLE
Request ADREPORT for logit_q_mat 

### ISSUE THREAD

**Issue by Cole-Monnahan-NOAA** [timjmiller/wham#62]
This regards getting uncertainty on catchability. 

In the devel branch there is only an ADREPORT if there is at least one [RE variance term](https://github.com/timjmiller/wham/blob/model_q/src/wham_v0.cpp#L668).

I think this should also include a flag for if there is a Ecov effect linked to q. Otherwise the user can't get uncertainty when that is enabled.

I was using an older version and got it with Ecov, and now that I updated it I can't seem to get it. I'm not sure how I was using this, but it looks like you made the change [here](https://github.com/timjmiller/wham/commit/fba34755d738da21d1284d6993e9a3062a5b0ffa#diff-5dddb539c736ba920b019e5634721ec289e033293cbf13c2fee0fd7edacae8eaR668).

Any chance you could update that to work for models with Ecov too, since those will be varying in time? Or maybe more generally even if there's just a single q per fleet, the user would want a SE in logit space so does it make sense to always ADREPORT it?

**Comment by timjmiller** [comment]
Thanks for finding this oversight. I will flag adreport to occur when there are Ecov effects on q as well. If there is no variation in time of q, the logit_q parameter vector is the estimated q on logit scale which is automatically adreported. If Ecov effects, logit_q is the intercept. if there are random effects, logit_q is the mean over the time series. If both, logit_q is the mean intercept over the time series.

I will close this issue when I get this fix on devel branch.

**Comment by Cole-Monnahan-NOAA** [comment]
TIm: I haven't parsed out the source that carefully so will trust you to implement. But you mean logit_q_mat right? From a user perspective if there's any variation on a q over time, it's nice to have SE on that in logit space. Thanks! I could do a PR but it's just a single line and seems overkill.

**Comment by timjmiller** [comment]
I only meant that when q is not time-varying you can get your SE from the logit_q parameter in the sdrep. I will change to adreport logit_q_mat when there are RE and/or Ecov effects on q.

**Comment by Cole-Monnahan-NOAA** [comment]
Tested and it works. I get annual SE when either Ecov or a RE structure is placed on catchability (or both). Thanks!
