### ISSUE TITLE
paa and do_osa 

### ISSUE THREAD

**Issue by gmoroncorrea** [timjmiller/wham#67]
A small constant needs to be added to paa_pred [here](https://github.com/timjmiller/wham/blob/fa8e16a74baeb7d548c63468e6f5d3cc438189db/src/age_comp_osa.hpp#L441), if not the dmultinom returns NaN when zeros are present. 

do_osa is not passed to other functions from get_acomp_ll when age_comp_model == 1, 2, 3, 4 ([see here](https://github.com/timjmiller/wham/blob/devel/src/age_comp_osa.hpp))

**Comment by timjmiller** [comment]
Thanks! I added this back in for multinomial [here](https://github.com/timjmiller/wham/commit/e93b610fd0cdbdaf250eec16ded0a9bf1893482a)

The OSA code has changed substantially and all models fitting should perform equivalently without having to specify any OSA flags. If you find this is not so, please open a separate issue.
