### ISSUE TITLE
FXSPR_Static

### ISSUE THREAD

**Issue by kcurti** [timjmiller/wham#68]
Per our discussion, I am creating in issue to document the following: 

When just running the base model without any projections, the FXSPR_static value does not match the F40 provided in the YPR-SPR table.

The fix you provided is to modify the setting in the input object that specifies which years are used to average spr/ypr inputs (when not running a projection, it is currently set as the first year).   

The following fix worked for plaice:
input$data$avg_years_ind = (input$data$n_years_model-5):(input$data$n_years_model-1)

**Comment by timjmiller** [comment]
This default setting has been changed appropriately from [this commit](https://github.com/timjmiller/wham/commit/7bba974c4d9ea8d772902be4d62512f20274a3ad)
