### ISSUE TITLE
data$n_fleets in set_catch is hard wired to 1 fleet

### ISSUE THREAD

**Issue by chengmatt** [timjmiller/wham#70]
Hi Tim,

[Line 52 ](https://github.com/timjmiller/wham/blob/28cab35ede66506dcaa73f7de8fc0334870893fc/R/set_catch.R#L52) in the set_catch function hard wires the number of fleets to 1. When I feed my data into prepare_wham_input, it outputs an object that has $n_fleet = 1, and agg_catch_sigma is only 1 column instead of multiple columns/fleets.

When I feed it into WHAM, the model runs fine (although it runs into convergence issues), but when I go to plot it, it results in the following error: Error in (log(catch) - pred_log_catch[1:length(years), ])/sigma : 
  non-conformable arrays

**Comment by timjmiller** [comment]
The $n_fleet issue should not be resolved on devel branch. Is the plotting issue caused by this error or a separate issue? If everything works with the updated install then please close the issue. Sorry it took so long to get around to this.

**Comment by chengmatt** [comment]
Hi Tim,

No problem - thanks for fixing this. I had initially closed the issue because it ended up running fine, but dropped some of the catch data (resulted in some bias).
