### ISSUE TITLE
Bug when running retros

### ISSUE THREAD

**Issue by GiancarloMCorrea** [timjmiller/wham#72]
Testing the new growth branch, I found a bug that made my model crash (R session aborted) and produce NaNs when running retros. The same issue happened (but the model did not crash, I don't know why yet) when using the devel branch. 

The problem is [here](https://github.com/timjmiller/wham/blob/2a2de41a6a0236af488930c4a0aa0c7cab86fcc2/src/wham_v0.cpp#L1234). avg_years_ind and XSPR_R_avg_yrs are not changed before running retros, so the indices are out of range and produced NaN or Inf when running _get_static_SPR_res_ function. 

This can be easily solved by adding [here](https://github.com/timjmiller/wham/blob/2a2de41a6a0236af488930c4a0aa0c7cab86fcc2/R/fit_peel.R#L26):

  temp$data$avg_years_ind = temp$data$avg_years_ind - peel
  temp$data$XSPR_R_avg_yrs = temp$data$XSPR_R_avg_yrs[1:n_years]

Hope this helps.

**Comment by timjmiller** [comment]
Thanks @GiancarloMCorrea. Now fixed on devel branch.
