### ISSUE TITLE
Incorrect indexing for CAA simulation?

### ISSUE THREAD

**Issue by ahart1** [timjmiller/wham#73]
simulate_data types are catch, indices, Ecov which can be referenced in the .cpp file as simulate_data(0), simulate_data(1), and simulate_data(2) respectively. However, the simulation code for CAA appears to be dependent on simulate_data(1) (index type) rather than simulate_data(0)  (catch type).

https://github.com/timjmiller/wham/blob/6c30301d5b68c2bb0c0330cc4f112432c7950dfd/src/wham_v0.cpp#L1039

**Comment by timjmiller** [comment]
Thanks @ahart1. Now fixed on devel branch.
