### ISSUE TITLE
Issue when calculating nll for compositional data

### ISSUE THREAD

**Issue by GiancarloMCorrea** [timjmiller/wham#76]
We have discussed this over email, but I wanted to make it formal.

There is an issue calculating the nll for compositional data when the predicted paa (or pal, or caal in growth branch) for a given year and fleet has a small number in it (specifically, the issue arises when a number < 1e-16 is present). 

For example, for the ddirichlet function, the issue happens [here](https://github.com/timjmiller/wham/blob/356082e53bcd5db1b69d6283045bd9793d656e31/src/age_comp_osa.hpp#L130), calculating log(sx) when sx = 0 so generating NaN. 

Likewise, I suspect that something similar happens [here](https://github.com/timjmiller/wham/blob/356082e53bcd5db1b69d6283045bd9793d656e31/src/age_comp_osa.hpp#L48), calculating p/(1-pUsed) when pUsed = 1 so generating NaN. 

Not sure how to fix this; the squeeze function might help.

**Comment by timjmiller** [comment]
This issue has been resolved on devel branch.
