### ISSUE TITLE
Run Ex2 fit_wham() with error " the condition has length > 1"

### ISSUE THREAD

**Issue by jutubuzou** [timjmiller/wham#84]
In the Ex2, when I run the fit_wham() with the do.osa TRUE, there was the error:
"Error in if (class(input$data$obs) == "list") input$data$obs <- as.data.frame(input$data$obs) : 
  the condition has length > 1"

And therefore, the results can't be generated. With error as:
"Error when reading the variable: 'agesvec'. Please check data and parameters.
In addition: Warning message:
In retape(set.defaults = FALSE) : Expected object. Got NULL."

But if I set the do.osa as FALSE, the model could run smoothly.

Any help or insight would be greatly appreciated!

**Comment by timjmiller** [comment]
This issue has been resolved on devel branch. Directions for installing this branch are in the README.
