### ISSUE TITLE
Error in plot.window(...) : need finite 'ylim' values

### ISSUE THREAD

**Issue by jimianelli** [timjmiller/wham#85]
plot_wham_output(mod=m2)
Generating plot files... Please wait ~30 seconds...
Error in plot.window(...) : need finite 'ylim' values
In addition: There were 17 warnings (use warnings() to see them)

**Comment by timjmiller** [comment]
Is this from running an example script? Which one?
What is the version and commit? Can be found from packageDescription("wham")

**Comment by timjmiller** [comment]
If this is still an issue just reopen the issue.
